[package]
name = "rust_blackjack"
version = "0.1.0"
authors = ["Douglas May <Dam1403@rit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
json = "*"
